site_name: Summit Language Docs
theme:
  name: material  # or any theme you like
nav:
  - Home: index.md
  - Basics:
      - Variables: variables.md
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
