site_name: Summit Language Docs
site_url: https://username.github.io/summit-docs
theme:
  name: material
nav:
  - Home: index.md
  - Variables: variables.md
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
